# Generated by Django 5.2.7 on 2025-10-26 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_name", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reference_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_exams",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
