# Generated by Django 5.2.7 on 2025-11-05 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_evaluation_body_fat_evaluation_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="evaluation_photos/%Y/%m/%d/")),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("FRENTE", "Frente"),
                            ("LADO", "Lado"),
                            ("COSTAS", "Costas"),
                        ],
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="evaluations.evaluation",
                    ),
                ),
            ],
        ),
    ]
