# Generated by Django 5.2.7 on 2025-10-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0003_labexam"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("front", "Frente"),
                            ("side", "Lado"),
                            ("back", "Costas"),
                        ],
                        max_length=20,
                    ),
                ),
                ("photo_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="evaluations.evaluation",
                    ),
                ),
            ],
        ),
    ]
