# Generated by Django 5.2.7 on 2025-10-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Feminino")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="professional_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DR", "Dr."),
                    ("DRA", "Dra."),
                    ("PHD", "PhD"),
                    ("MTR", "Mestre"),
                    ("ESP", "Especialista"),
                    ("NUT", "Nutricionista"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
