# Generated by Django 5.2.7 on 2025-10-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anamnesis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anamnesis",
            name="height",
        ),
    ]
