# Generated by Django 5.2.7 on 2025-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anamnesis", "0002_remove_anamnesis_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="anamnesis",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
