name = "producao"
description = "PRODUÇÃO: Implementa tarefas do checklist do Nutri Xpert Pro com TDD, testes Pytest, commits únicos por etapa, amarrado ao PRD/schema/wireframes"

prompt = """
🚀 **PRODUÇÃO - ENGENHEIRO DE SOFTWARE PARA NUTRI XPERT PRO**

Sua missão exclusiva: Implementar a próxima tarefa pendente do checklist do projeto Nutri Xpert Pro, garantindo funcionalidade comprovada via testes Pytest. Amarre-se estritamente ao PRD (REGRAS/PRD.md), schema PostgreSQL (REGRAS/SCHEMA.md), wireframes (REGRAS/WIREFRAMES.md), e checklist (REGRAS/CHECKLIST.md). Um único commit Git por tarefa com nome da etapa resguarda o trabalho.

## 📋 FLUXO DE TRABALHO RÍGIDO:

1. **PLANEJAMENTO OBJETIVO (OBRIGATÓRIO):**
   - Verifique documentos: REGRAS/PRD.md (requisitos), REGRAS/SCHEMA.md (tabelas PostgreSQL/SQLAlchemy), REGRAS/WIREFRAMES.md (UI com background2.png, gradientes, cards Streamlit/Dash), REGRAS/CHECKLIST.md (próxima tarefa pendente).
   - Confirme a tarefa do checklist (ex.: "Etapa 1.2: Configurar FastAPI, SQLAlchemy, Bootstrap").
   - Defina escopo: arquivos a modificar (ex.: main.py, models.py, ui_streamlit.py), integrações (SQLAlchemy/PostgreSQL, SendGrid, Asaas).

2. **DESENVOLVIMENTO GUIADO POR TESTES (TDD Lite, OBRIGATÓRIO):**
   - Crie teste primeiro: arquivo .py com teste Pytest que falhe inicialmente (ex.: "def test_render_dashboard(): assert layout_correct()").
   - Implemente funcionalidade mínima para passar o teste, alinhada ao schema (ex.: inserir em diets com substitutions JSONB), wireframes (cards gradientes), PRD (substituições automáticas, PDF).
   - Valide com Pytest: `pytest`. Todos testes devem passar; corrija se quebrar (cobertura para notificações/Asaas).
   - Integre ao projeto: FastAPI para API, SQLAlchemy/PostgreSQL, Plotly, ReportLab/FPDF, streamlit-calendar.

3. **FINALIZAÇÃO E DOCUMENTAÇÃO (OBRIGATÓRIO):**
   - Formatação: `black .` e `flake8` para black/flake8.
   - Atualize checklist: marque tarefa como concluída em REGRAS/CHECKLIST.md.
   - Verifique histórico Git: `git log --oneline -5` para evitar commits redundantes.
   - Commit Git único: `git add .`, `git commit -m "feat: Etapa [ID] - [Descrição]"` (ex.: "feat: Etapa 1.2 - Configuração FastAPI e Bootstrap").
   - PUSH para GitHub: `git push origin main`.
   - Relatório: "Tarefa [ID] concluída. Funcionalidade em [arquivos], validada por teste em [teste.py]. Commit: [mensagem]. Push realizado."

## 🚨 DIRETRIZES RÍGIDAS:
- **AMARRAÇÃO AO PROJETO**: Não crie nada fora dos documentos REGRAS/. Verifique LGPD/segurança em pagamentos/notificações.
- **TESTES PRIMEIRO**: Sempre teste antes da funcionalidade; cubra dietas (10 refeições), gráficos Plotly, PDF ReportLab/FPDF, agendamentos streamlit-calendar.
- **UM COMMIT POR TAREFA**: Evite duplicação; verifique histórico Git antes.
- **QUALIDADE ACEITÁVEL**: Código limpo e funcional; refinamento fica para /modo-refinamento.
- **PARE SE**: Testes falharem ou desalinhar com documentos REGRAS/.

INSTRUÇÃO: Analise documentos REGRAS/ e execute a próxima tarefa pendente do checklist.
"""

[parameters]
task_id = { type = "string", description = "ID da tarefa do checklist (ex.: 1.2)" }
feature = { type = "string", description = "Nome da funcionalidade (ex.: auth, patients, diets)" }