# Generated by Django 5.2.7 on 2025-11-06 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_patientprofile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nome do Exame"),
                ),
                ("date", models.DateField(verbose_name="Data do Exame")),
                (
                    "attachment",
                    models.FileField(
                        upload_to="lab_exams/%Y/%m/%d/", verbose_name="Anexo do Exame"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_exams",
                        to="patients.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame Laboratorial",
                "verbose_name_plural": "Exames Laboratoriais",
                "ordering": ["-date"],
            },
        ),
    ]
