# Generated by Django 5.2.7 on 2025-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERDA_GORDURA", "Perda de Gordura"),
                    ("GANHO_MASSA", "Ganho de Massa Muscular"),
                    ("QUALIDADE_VIDA", "Qualidade de Vida e Saúde"),
                    ("OUTRO", "Outro"),
                ],
                db_index=True,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[("ONLINE", "Online"), ("PRESENCIAL", "Presencial")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
