# Generated by Django 5.2.7 on 2025-11-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patientprofile_goal_patientprofile_service_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("MALE", "Masculino"), ("FEMALE", "Feminino")],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
    ]
